### PR TITLE
csharp OpenSSL phase 2

### PR DESCRIPTION
**Pull request by jgowdy**
C# OpenSSL phase 2 is largely about modifying AppEncryption to support IConfiguration based configuration instead of or complementary to the existing builder pattern, which also enables passing IConfiguration down to the SecureMemory layer for selection of the OpenSSL secure heap.

See also this PR to SecureMemory which AppEncryption is now updated to: https://github.com/godaddy/asherah/pull/324

Phase 3 should be the final PR which will move to using native OpenSSL crypto facilties, which allows us to never have encryption keys in a decrypted state in managed memory.

### CODE REVIEW

**Comment by jgowdy** [comment]
https://github.com/godaddy/asherah/pull/318#issuecomment-705855701

**Comment by jgowdy** [comment]
https://github.com/godaddy/asherah/blob/baa290e41afad69b5a98183003ccce53b7c37363/csharp/AppEncryption/README.md#configuration

**Comment by jgowdy** [comment]
Code coverage is as high as possible, uncovered lines are largely fatal and difficult to test edge cases.

**Comment by jgowdy** [comment]
I'm changing direction on this

**Comment by lyricnz** [comment]
@jgowdy whatever happened with this, man?  "changed direction" to what?   we are still having issues with mlock exhaustion (on AWS Lambda environments), and were hoping for openssl-heap based solution to avoid excessive mlock.

**Pull request closed without merging**
