### PR TITLE
feat: AWS SDK Go V2

### PR DESCRIPTION
**Pull request by JoseAngel1196**
To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [ ] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the API in any way?

* [ ] Yes (backward compatible)
* [ ] No (breaking changes)

## What's new?
-

### CODE REVIEW

**Comment by aka-bo** [comment]
@JoseAngel1196 please see the draft PR #1041 for the current thinking around the initial aws-v1 migration. The main idea here is to leverage type aliases to maintain backwards compatibility.

**Comment by JoseAngel1196** [comment]
> @JoseAngel1196 please see the draft PR #1041 for the current thinking around the initial aws-v1 migration. The main idea here is to leverage type aliases to maintain backwards compatibility.

nice! Will wait working on this PR until you finish there!

**Comment by sushantmimani** [comment]
> > @JoseAngel1196 please see the draft PR #1041 for the current thinking around the initial aws-v1 migration. The main idea here is to leverage type aliases to maintain backwards compatibility.
> 
> nice! Will wait to work on this PR until you finish there!

#1041 has been merged now.

**Comment by JoseAngel1196** [comment]
> > > @JoseAngel1196 please see the draft PR #1041 for the current thinking around the initial aws-v1 migration. The main idea here is to leverage type aliases to maintain backwards compatibility.
> > 
> > 
> > nice! Will wait to work on this PR until you finish there!
> 
> @JoseAngel1196 #1041 has been merged now.

Sounds good, going to be working on this week.

**Pull request closed without merging**
